[tool.poetry]
name = "forwardkinematics"
version = "0.5.6"
description = "\"Light-weight implementation of forward kinematics using casadi.\""
authors = ["Max Spahn <m.spahn@tudelft.nl>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/maxspahn/forwardKinematics.git"
repository = "https://github.com/maxspahn/forwardKinematics.git"


[tool.poetry.dependencies]
python = "^3.6,<3.11"
casadi = "<=3.5.5"
numpy = "^1.15.5"
urdf_parser_py = ">=0.0.3"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
